<style>
/*This styles are generated by theme options*/

body{
	font-size: <?php echo get_option('theme_font_size')?>;
}

p{
	color: <?php echo get_option('body-color')?>;
	font-size:<?php echo get_option('body-size')?>px;
	line-height: <?php echo get_option('body-line-height')?>px;
}

a{
	color: <?php echo get_option('link-color')?>;
}
a:hover{
	color: <?php echo get_option('link-hover-color')?>;
}

a:active{
	color: <?php echo get_option('link-active-color')?>;
}

.navbar .nav > li > a{
	color: <?php echo get_option('nav-color')?>;
}

/*Top level menu item*/
.navbar-inverse .nav > li > a:focus, 
.navbar-inverse .nav > li > a:hover{ 
	color: <?php echo get_option('nav-hover-color')?>;
}

.navbar .nav > li.current_page_item a,
.navbar .nav > li.current-menu-item a,
#menu-footer-menu li.current_page_item a,
#menu-footer-menu li.current-menu-item a,
#menu-footer-menu-1 li.current_page_item a,
#menu-footer-menu-1 li.current-menu-item a{
	color: <?php echo get_option('nav-active-color')?>;
}


/*Header Background*/
.header-wrapper{
	background: <?php echo get_option('header-bk-color')?>;
}


/*Sidebar*/
#custom-side{
	width: <?php echo get_option('sidebar-width')?>px;
}


.container{
	max-width: <?php echo get_option('container-width')?>px;;
}

/*Pagination*/

.wp-paginate a{
	background: <?php echo get_option('pagination-bk-color');?>!important;
	color: <?php echo get_option('pagination-color');?>!important;
}
.wp-paginate a:hover{
	background: <?php echo get_option('pagination-hover-bk-color');?>!important;
	color: <?php echo get_option('pagination-hover-color');?>!important;
}

.wp-paginate .current{
	background: <?php echo get_option('pagination-act-bk-color');?>!important;
	color: <?php echo get_option('pagination-act-color');?>!important;
}


/*Read more button*/

.more{
	color: <?php echo get_option('readmore-color');?>;
	background: <?php echo get_option('readmore-bk-color');?>;
}
.more:hover{
	color: <?php echo get_option('readmore-hover-color');?>;
	background: <?php echo get_option('readmore-hover-bk-color');?>;
}

/*Submit button*/

#wp-submit, 
#reg-submit, 
.wpcf7-submit{
	background: <?php echo get_option('submit-bk-color');?>;
	color: <?php echo get_option('submit-color');?>;
}


/*Category*/
.lol{
	background: <?php echo get_option('cat-lol')?>;
}

.dota2{
	background: <?php echo get_option('cat-dota')?>;
}

.csgo{
	background: <?php echo get_option('cat-csgo')?>;
}

.esports{
	background: <?php echo get_option('cat-esports')?>;
}
</style>